name: Github Pages
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: head

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: yarn

      - name: Build package
        run: |
          bundle exec rake
          yarn install --frozen-lockfile
          yarn build

      - name: Test package
        run: yarn test
